In [30]:
import numpy as np

In [44]:
x = [[1,2,3,4],
     [5,6,7,8],
     [9,10,11,12],
     [13,14,15,16]]

In [45]:
inp = np.array(x)
inp

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [33]:
oup = [[13,9,5,1],
       [14,10,6,2],
       [15,11,7,3],
       [16,12,8,4]]

In [136]:
x = np.array([range(1,6),range(6,11),range(11,16),range(16,21),range(21,26)])

In [35]:
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [36]:
result[[21,16,11,6,1],
       [22,17,12,7,2],
       [23,18,13,8,3],
       [24,19,14,9,4],
       [25,20,15,10,5]]

[[21, 16, 11, 6, 1],
 [22, 17, 12, 7, 2],
 [23, 18, 13, 8, 3],
 [24, 19, 14, 9, 4],
 [25, 20, 15, 10, 5]]

In [37]:
[[ 1,  2,  3,  4,  5],
 [ 6,  7,  8,  9, 10],
 [11, 12, 13, 14, 15],
 [16, 17, 18, 19, 20],
 [21, 22, 23, 24, 25]
]

[[1, 2, 3, 4, 5],
 [6, 7, 8, 9, 10],
 [11, 12, 13, 14, 15],
 [16, 17, 18, 19, 20],
 [21, 22, 23, 24, 25]]

In [42]:
n = len(x[:,:])

In [ ]:
i+j+i+j=20

Step 1 : add to j
a. if (j+n)==n then i=i, j=j+n
b. elif j+n>n then i=j and j=n

Step 2 : add to i
a. if (i+n)==n then i=n, j=n
b. elif i+n>n then j=n-i and i=n

Step 3 : subtract to j
a. if j-n=0 then i=n,j=0
b. if j-n<0 then i=j,j=0

step4 : subtract to i
a. if j==0 and i!=0 then j=(n-i), i=0

    
  step1 step2 step3 step4
00 -> 04 -> 44 -> 40 -> 00
01 -> 14 -> 43 -> 30 -> 01
02 -> 24 -> 42 -> 20 -> 02
03 -> 34 -> 41 -> 10 -> 03

In [46]:
x
[[1, 2, 3, 4], 
 [5, 6, 7, 8], 
 [9, 10, 11, 12], 
 [13, 14, 15, 16]]


[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]

In [54]:
inp

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [61]:
n = len(inp)

In [62]:
n

4

In [63]:
inp[1:n-1,1:n-1]


array([[ 6,  7],
       [10, 11]])

======================= writing function ===========================

In [64]:
x = np.array([range(1,6),range(6,11),range(11,16),range(16,21),range(21,26)])

In [65]:
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
result=[[21,16,11,6,1],
       [22,17,12,7,2],
       [23,18,13,8,3],
       [24,19,14,9,4],
       [25,20,15,10,5]]

Algo :
    
Step 1 : add to j
a. if (j+n)==n then i=i, j=j+n
b. elif j+n>n then i=j and j=n

Step 2 : add to i
a. if (i+n)==n then i=n, j=n
b. elif i+n>n then j=n-i and i=n

Step 3 : subtract to j
a. if j-n=0 then i=n,j=0
b. if j-n<0 then i=j,j=0

step4 : subtract to i
a. if j==0 and i!=0 then j=(n-i), i=0

    
  step1 step2 step3 step4
00 -> 04 -> 44 -> 40 -> 00
01 -> 14 -> 43 -> 30 -> 01
02 -> 24 -> 42 -> 20 -> 02
03 -> 34 -> 41 -> 10 -> 03

In [258]:
x = np.array([range(1,6),range(6,11),range(11,16),range(16,21),range(21,26)])

In [256]:
n=len(x)
n

5

In [257]:
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [259]:
n=len(x)
start=0
end=n
x = x[start:end,start:end]
n=len(x)

#i and j are the co-ordinates of the matrix
#temp1 and temp2 are the value holders of the matrix

source_ele=x[0,0]

for j in range(0,n-1):
    i=0
    x = x[start:end,start:end]
    n=len(x)
    
    source_ele = x[i,j]

    def cycle1_add_to_j(i,j,x):
        if(j+n)==n:
            i,j=i,j+n-1
        elif(j+n>n):
            i=j
            j=n-1
        return i,j
    i,j=cycle1_add_to_j(i,j,x)
    temp1=x[i,j]
    x[i,j]=source_ele
    source_ele=temp1

    def cycle2_add_to_i(i,j,x):
        if i+n==n:
            i,j=n-1,n-1
        elif i+n>n:
            j=n-1-i
            i=n-1

        return i,j
    i,j=cycle2_add_to_i(i,j,x)
    temp1=x[i,j]
    x[i,j]=source_ele
    source_ele=temp1

    def cycle3_subtract_to_j(i,j,x):
        if j-n==0:
            i=n
            j=0
        elif j-n<0:
            i=j
            j=0
        return i,j
    i,j=cycle3_subtract_to_j(i,j,x)
    temp1=x[i,j]
    x[i,j]=source_ele
    source_ele=temp1

    def cycle4_subtract_to_i(i,j,x):
        if j==0 and i!=0:
            j=n-1-i
            i=0
        return i,j
    i,j=cycle4_subtract_to_i(i,j,x)
    temp1=x[i,j]
    x[i,j]=source_ele
    source_ele=temp1

In [260]:
x

array([[21, 16, 11,  6,  1],
       [22,  7,  8,  9,  2],
       [23, 12, 13, 14,  3],
       [24, 17, 18, 19,  4],
       [25, 20, 15, 10,  5]])

========================================================================

In [381]:
x = np.array([range(1,6),range(6,11),range(11,16),range(16,21),range(21,26)])

In [382]:
n=len(x)
n

5

In [383]:
d1={}

In [384]:
#1st iteration
n=len(x)

start=0
end=n
while start<end-1:
    print("start and end are",start,end)
    x = x[start:end,start:end]
    n=len(x)

#i and j are the co-ordinates of the matrix
#temp1 and temp2 are the value holders of the matrix

    source_ele=x[0,0]

    for j in range(0,n-1):
        i=0
        source_ele = x[i,j]

        def cycle1_add_to_j(i,j,x):
            if(j+n)==n:
                i,j=i,j+n-1
            elif(j+n>n):
                i=j
                j=n-1
            return i,j
        i,j=cycle1_add_to_j(i,j,x)
        temp1=x[i,j]
        x[i,j]=source_ele
        source_ele=temp1

        def cycle2_add_to_i(i,j,x):
            if i+n==n:
                i,j=n-1,n-1
            elif i+n>n:
                j=n-1-i
                i=n-1

            return i,j
        i,j=cycle2_add_to_i(i,j,x)
        temp1=x[i,j]
        x[i,j]=source_ele
        source_ele=temp1

        def cycle3_subtract_to_j(i,j,x):
            if j-n==0:
                i=n
                j=0
            elif j-n<0:
                i=j
                j=0
            return i,j
        i,j=cycle3_subtract_to_j(i,j,x)
        temp1=x[i,j]
        x[i,j]=source_ele
        source_ele=temp1

        def cycle4_subtract_to_i(i,j,x):
            if j==0 and i!=0:
                j=n-1-i
                i=0
            return i,j
        i,j=cycle4_subtract_to_i(i,j,x)
        temp1=x[i,j]
        x[i,j]=source_ele
        source_ele=temp1
        print(x)
    d1[n]=x
    start+=1
    end-=1
print(x)

start and end are 0 5
[[21  2  3  4  1]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [25 22 23 24  5]]
[[21 16  3  4  1]
 [ 6  7  8  9  2]
 [11 12 13 14 15]
 [24 17 18 19 20]
 [25 22 23 10  5]]
[[21 16 11  4  1]
 [ 6  7  8  9  2]
 [23 12 13 14  3]
 [24 17 18 19 20]
 [25 22 15 10  5]]
[[21 16 11  6  1]
 [22  7  8  9  2]
 [23 12 13 14  3]
 [24 17 18 19  4]
 [25 20 15 10  5]]
start and end are 1 4
[[17  8  7]
 [12 13 14]
 [19 18  9]]
[[17 12  7]
 [18 13  8]
 [19 14  9]]
[[17 12  7]
 [18 13  8]
 [19 14  9]]


In [385]:
d1

{5: array([[21, 16, 11,  6,  1],
        [22, 17, 12,  7,  2],
        [23, 18, 13,  8,  3],
        [24, 19, 14,  9,  4],
        [25, 20, 15, 10,  5]]),
 3: array([[17, 12,  7],
        [18, 13,  8],
        [19, 14,  9]])}

In [355]:
end

4

In [356]:
d1

{5: array([[21, 16, 11,  6,  1],
        [22,  7,  8,  9,  2],
        [23, 12, 13, 14,  3],
        [24, 17, 18, 19,  4],
        [25, 20, 15, 10,  5]])}

In [357]:
x

array([[21, 16, 11,  6,  1],
       [22,  7,  8,  9,  2],
       [23, 12, 13, 14,  3],
       [24, 17, 18, 19,  4],
       [25, 20, 15, 10,  5]])

In [358]:
n=len(x)

In [359]:
#1st iteration
n=len(x)

x = x[start:end,start:end]
n=len(x)
#i and j are the co-ordinates of the matrix
#temp1 and temp2 are the value holders of the matrix

source_ele=result[0,0]

for j in range(0,n-1):
    print("i and j are",i,j)
    print("x is",x)
    print("n is ",n)
    i=0
    
    source_ele = x[i,j]

    def cycle1_add_to_j(i,j,x):
        if(j+n)==n:
            i,j=i,j+n-1
        elif(j+n>n):
            i=j
            j=n-1
        return i,j
    i,j=cycle1_add_to_j(i,j,x)
    temp1=x[i,j]
    x[i,j]=source_ele
    source_ele=temp1

    def cycle2_add_to_i(i,j,x):
        if i+n==n:
            i,j=n-1,n-1
        elif i+n>n:
            j=n-1-i
            i=n-1

        return i,j
    i,j=cycle2_add_to_i(i,j,x)
    temp1=x[i,j]
    x[i,j]=source_ele
    source_ele=temp1

    def cycle3_subtract_to_j(i,j,x):
        if j-n==0:
            i=n
            j=0
        elif j-n<0:
            i=j
            j=0
        return i,j
    i,j=cycle3_subtract_to_j(i,j,x)
    temp1=x[i,j]
    x[i,j]=source_ele
    source_ele=temp1

    def cycle4_subtract_to_i(i,j,x):
        if j==0 and i!=0:
            j=n-1-i
            i=0
        return i,j
    i,j=cycle4_subtract_to_i(i,j,x)
    temp1=x[i,j]
    x[i,j]=source_ele
    source_ele=temp1
    d1[n]=x
    
start+=1
end-=1

i and j are 0 0
x is [[ 7  8  9]
 [12 13 14]
 [17 18 19]]
n is  3
i and j are 0 1
x is [[17  8  7]
 [12 13 14]
 [19 18  9]]
n is  3


In [366]:
x = np.array([range(1,6),range(6,11),range(11,16),range(16,21),range(21,26)])
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [361]:
d1

{5: array([[21, 16, 11,  6,  1],
        [22, 17, 12,  7,  2],
        [23, 18, 13,  8,  3],
        [24, 19, 14,  9,  4],
        [25, 20, 15, 10,  5]]),
 3: array([[17, 12,  7],
        [18, 13,  8],
        [19, 14,  9]])}

In [362]:
start

2

In [363]:
end

3

In [ ]:
when start>end, it is solved!

In [364]:
y = d1[5]

In [365]:
y

array([[21, 16, 11,  6,  1],
       [22, 17, 12,  7,  2],
       [23, 18, 13,  8,  3],
       [24, 19, 14,  9,  4],
       [25, 20, 15, 10,  5]])

In [307]:
x

array([[21, 16, 11,  6,  1],
       [22,  7,  8,  9,  2],
       [23, 12, 13, 14,  3],
       [24, 17, 18, 19,  4],
       [25, 20, 15, 10,  5]])

In [305]:
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [288]:
n=len(x)

start=0+1
end=n-1
x = x[start:end,start:end]
print(x)
np.array(x)

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [298]:
#2nd iteration

n=len(x)

start=0+1
end=n-1
x = x[start:end,start:end]
x = np.array(x)
print(x)

source_ele=result[0,0]

for j in range(0,n-1):
    i=0
    x = x[start:end,start:end]
    n=len(x)
    
    source_ele = x[i,j]

    def cycle1_add_to_j(i,j,x):
        if(j+n)==n:
            i,j=i,j+n-1
        elif(j+n>n):
            i=j
            j=n-1
        return i,j
    i,j=cycle1_add_to_j(i,j,x)
    temp1=x[i,j]
    x[i,j]=source_ele
    source_ele=temp1

    def cycle2_add_to_i(i,j,x):
        if i+n==n:
            i,j=n-1,n-1
        elif i+n>n:
            j=n-1-i
            i=n-1

        return i,j
    i,j=cycle2_add_to_i(i,j,x)
    temp1=x[i,j]
    x[i,j]=source_ele
    source_ele=temp1

    def cycle3_subtract_to_j(i,j,x):
        if j-n==0:
            i=n
            j=0
        elif j-n<0:
            i=j
            j=0
        return i,j
    i,j=cycle3_subtract_to_j(i,j,x)
    temp1=x[i,j]
    x[i,j]=source_ele
    source_ele=temp1

    def cycle4_subtract_to_i(i,j,x):
        if j==0 and i!=0:
            j=n-1-i
            i=0
        return i,j
    i,j=cycle4_subtract_to_i(i,j,x)
    temp1=x[i,j]
    x[i,j]=source_ele
    source_ele=temp1

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


IndexError: index 1 is out of bounds for axis 1 with size 1

In [294]:
result

array([[21, 16, 11,  6,  1],
       [22,  7,  8,  9,  2],
       [23, 12, 13, 14,  3],
       [24, 17, 18, 19,  4],
       [25, 20, 15, 10,  5]])

In [273]:
x

array([[21, 16, 11,  6,  1],
       [22,  7,  8,  9,  2],
       [23, 12, 13, 14,  3],
       [24, 17, 18, 19,  4],
       [25, 20, 15, 10,  5]])